### PR TITLE
V1.0.0/sub bio detail

### PR DESCRIPTION
**Pull request by atahantutar**
#19 
image

- Location, website and date of birth fields have been added to the user page area.

#59 
image

- User tags and links in the post section are redirected.

### CODE REVIEW

**Comment by harundogdu** [comment]
@atahantutar Conflict'leri çözelim abi

**Comment by harundogdu** [comment]
@atahantutar ne durumdayız?

**Comment by atahantutar** [comment]
@harundogdu conflictleri çözdüm abi

**Comment by harundogdu** [comment]
@atahantutar hala var conflict, tamamlayalım ya da kapatayım.

**Pull request merged**
